
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/cicdproject
permissions:
  - object: /home/ec2-user/cicdproject/
    owner: cicd-test
    group: cicd-test

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: cicd-test
